### ISSUE TITLE
pip3 install tdmgr fails on Ubuntu/RPI

### ISSUE THREAD

**Issue by Masterz69** [jziolkowski/tdm#116]
Ubuntu 20 server edition / Raspberry Pi 4B 4Gb

ubuntu@rpi4:~$ sudo pip3 install tdmgr
Collecting tdmgr
  Downloading tdmgr-0.2.8-py3-none-any.whl (108 kB)
     |████████████████████████████████| 108 kB 219 kB/s
Collecting paho-mqtt>=1.4
  Using cached paho-mqtt-1.5.1.tar.gz (101 kB)
Collecting PyQt5>=5.12
  Downloading PyQt5-5.15.2.tar.gz (3.3 MB)
     |████████████████████████████████| 3.3 MB 571 kB/s
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... error
    ERROR: Command errored out with exit status 1:
     command: /usr/bin/python3 /tmp/tmpc0_c_86c prepare_metadata_for_build_wheel /tmp/tmpz894ah36
         cwd: /tmp/pip-install-klouc1a6/PyQt5
    Complete output (31 lines):
    Traceback (most recent call last):
      File "/tmp/tmpc0_c_86c", line 126, in prepare_metadata_for_build_wheel
        hook = backend.prepare_metadata_for_build_wheel
    AttributeError: module 'sipbuild.api' has no attribute 'prepare_metadata_for_build_wheel'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/tmpc0_c_86c", line 280, in <module>
        main()
      File "/tmp/tmpc0_c_86c", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/tmp/tmpc0_c_86c", line 130, in prepare_metadata_for_build_wheel
        return _get_wheel_metadata_from_wheel(backend, metadata_directory,
      File "/tmp/tmpc0_c_86c", line 159, in _get_wheel_metadata_from_wheel
        whl_basename = backend.build_wheel(metadata_directory, config_settings)
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/sipbuild/api.py", line 51, in build_wheel
        project = AbstractProject.bootstrap('pep517')
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/sipbuild/abstract_project.py", line 83, in bootstrap
        project.setup(pyproject, tool, tool_description)
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 479, in setup
        self.apply_user_defaults(tool)
      File "project.py", line 63, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/pyqtbuild/project.py", line 79, in apply_user_defaults
        super().apply_user_defaults(tool)
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/sipbuild/project.py", line 225, in apply_user_defaults
        self.builder.apply_user_defaults(tool)
      File "/tmp/pip-build-env-vwt7tgqi/overlay/lib/python3.8/site-packages/pyqtbuild/builder.py", line 66, in apply_user_defaults
        raise PyProjectOptionException('qmake',
    sipbuild.pyproject.PyProjectOptionException
    ----------------------------------------
ERROR: Command errored out with exit status 1: /usr/bin/python3 /tmp/tmpc0_c_86c prepare_metadata_for_build_wheel /tmp/tmpz894ah36 Check the logs for full command output.

**Comment by jziolkowski** [comment]
do you have latest versions of pip, setuptools and wheel installed?

**Comment by Jason2866** [comment]
It is a RPi QT5 installation issue. See https://github.com/tasmota/tasmotizer/issues/26#issuecomment-670808652

**Comment by jziolkowski** [comment]
hint of a solution: https://github.com/tasmota/tasmotizer/issues/71

**Comment by Jason2866** [comment]
Any news? Suggested solution tried?

**Comment by Jason2866** [comment]
Closing since there is no feedback
