### ISSUE TITLE
too many devices?

### ISSUE THREAD

**Issue by mackuy** [jziolkowski/tdm#126]
Hi, installed and started tdmgr in a MAC (Big Sur OS -2018-32Gb). Configured MQTT (many of my devices are in 5.8 version only a few are in 6 and only one in 9), connected and it gives me an error (seems to be a sized array or something related to the number of tasmota devices, I have more than 50), the error is:

Traceback (most recent call last):
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/Util/models.py", line 109, in data
    return d.color()
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/Util/__init__.py", line 323, in color
    68: self.setoption(68)
  File "/Users/xxx/Library/Python/3.8/lib/python/site-packages/Util/__init__.py", line 338, in setoption
    options = int(so[reg], 16)
IndexError: list index out of range
zsh: abort      tdmgr.py

Need I upgrade to more than 6 version the oldest devices before run tdmgr?

**Comment by Jason2866** [comment]
See https://github.com/jziolkowski/tdm#minimum-fully-supported-tasmota-firmware-version-66017

**Comment by mackuy** [comment]
Tks
