### ISSUE TITLE
TDM Crash on clicking Buttons, Switches or Power menus

### ISSUE THREAD

**Issue by CyrilB1531** [jziolkowski/tdm#200]
In Python 3.10.4 
Buttons, Switches or Power menu button crashes with the following errors:
Traceback (most recent call last):
  File "tdm\GUI\Devices.py", line 513, in configureSwitches
    switches = SwitchesDialog(self.device)
  File "tdm\GUI\Switches.py", line 31, in __init__
    self.sm = CommandMultiSelect(
  File "tdm\GUI\__init__.py", line 387, in __init__
    for i, val in enumerate(value):
TypeError: 'NoneType' object is not iterable

or:
 File "tdm\GUI\Devices.py", line 472, in configureButtons
    buttons = ButtonsDialog(self.device)
  File "tdm\GUI\XXXXX.py", line 34, in __init__
    cw = Command("SetOption{}".format(so), setoptions[str(so)], self.device.setoption(so))
TypeError: 'module' object is not subscriptable

**Comment by jziolkowski** [comment]
fixed, check latest release
