### ISSUE TITLE
TDM-010 develop crashes on Windows11 at MQTT connection

### ISSUE THREAD

**Issue by barbudor** [jziolkowski/tdm#220]
Hi @jziolkowski 

Sorry to say but TDM develop as of tonight (https://github.com/jziolkowski/tdm/commit/73fe1388019a6c3ef8115edbd6e019af889f6161) crashes as soon as I choose "Connect" in the MQTT menu

Running Python 3.10.8 on Windows 11
Requirements installed are:
paho_mqtt>=1.4 : 1.6.1
PyQt5<6,>=5.14.2 : 5.15.7
PyQt5-sip<13,>=12.11 : 12.11.0
PyQt5-Qt5>=5.15.0 5.15.2

Logs in the console:
- Launching TDM and before connetcing to MQTT:
```
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
```

- As soon as I try to connect:
```
Traceback (most recent call last):
  File "D:\Projets\repos\tdm\GUI\delegates\devices.py", line 146, in paint
    self.draw_rssi_pixmap(index, option, p)
  File "D:\Projets\repos\tdm\GUI\delegates\devices.py", line 227, in draw_rssi_pixmap
    px_rect = QRect(option.rect.x() + 2, px_y, 24, 24)
TypeError: arguments did not match any overloaded call:
  QRect(): too many arguments
  QRect(int, int, int, int): argument 2 has unexpected type 'float'
  QRect(QPoint, QPoint): argument 1 has unexpected type 'int'
  QRect(QPoint, QSize): argument 1 has unexpected type 'int'
  QRect(QRect): argument 1 has unexpected type 'int'
```

Log file (with loglevel=DEBUG):
```
2022-12-13 21:04:10 [INFO] ### TDM START ###
2022-12-13 21:04:17 [INFO] MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-tvsamsung/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-tvsamsung/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-3dprinter/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-3dprinter/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-pcvalou/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-pcvalou/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-barbuxps/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-barbuxps/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/sns-terrasse/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/sns-terrasse/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-wifi1er/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-wifi1er/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-washing/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-washing/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-pump/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-pump/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/esp32dev3/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/esp32dev3/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/ble-bridge/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/ble-bridge/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/esp32c3dev/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/esp32c3dev/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/skt-nuci5/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/skt-nuci5/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/rfbridge/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/rfbridge/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/sns-envsalon/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/sns-envsalon/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/zbbridge/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/zbbridge/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/sw-chambre1/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/sw-chambre1/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/unconf_2C3AE80F4E31/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/unconf_2C3AE80F4E31/FullTopic
2022-12-13 21:04:17 [INFO] DISCOVERY: LWT from an unknown device tele/htr-smallroom/LWT
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Asking an unknown device for FullTopic at cmnd/htr-smallroom/FullTopic
2022-12-13 21:04:17 [DEBUG] DISCOVERY: topic stat/skt-tvsamsung/FULLTOPIC is matched by fulltopic %prefix%/%topic%/
2022-12-13 21:04:17 [INFO] DISCOVERY: Discovered topic=skt-tvsamsung with fulltopic=%prefix%/%topic%/
2022-12-13 21:04:17 [DEBUG] DISCOVERY: Sending initial query to topic skt-tvsamsung
```

Thanks

**Comment by jziolkowski** [comment]
The `QWidget::insertAction: Attempt to insert null action` error: I need exact number of occurences. I have a hunch.

**Comment by barbudor** [comment]
This is exactly what I have by just launching the ./tdmgr.py (pulled from tonight) wihtout auto-connect:
```
$ ./tdmgr.py
### TDM START ###
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
QWidget::insertAction: Attempt to insert null action
```

Then connecting: All good
```
MQTT: Subscribed to tele/#, stat/#, cmnd/#, +/tele/#, +/stat/#, +/cmnd/#
DISCOVERY: LWT from an unknown device tele/esp32dev3/LWT
DISCOVERY: LWT from an unknown device tele/esp32c3dev/LWT
DISCOVERY: LWT from an unknown device tele/rfbridge/LWT
DISCOVERY: LWT from an unknown device tele/zbbridge/LWT
DISCOVERY: LWT from an unknown device tele/unconf_2C3AE80F4E31/LWT
```

No more messages then

Let me know if you need anything more

**Comment by jziolkowski** [comment]
Ok, so it still crashes or not?

**Comment by barbudor** [comment]
No, not since the integer divide was solved
Seems to work fine now
