### ISSUE TITLE
Missing dependency for setuptools

### ISSUE THREAD

**Issue by RichieB2B** [jziolkowski/tdm#299]
After a succesful `pip install tdmgr` on MacOS Sequoia 15.0.1 (MacBook M1) I got this error:

```
% tdmgr
Traceback (most recent call last):
  File "/Users/my-user/tasmota/tdm/venv/bin/tdmgr", line 5, in <module>
    from tdmgr.run import start
  File "/Users/my-user/tasmota/tdm/venv/lib/python3.12/site-packages/tdmgr/run.py", line 13, in <module>
    from tdmgr.GUI.dialogs.main import MainWindow
  File "/Users/my-user/tasmota/tdm/venv/lib/python3.12/site-packages/tdmgr/GUI/dialogs/__init__.py", line 1, in <module>
    from tdmgr.GUI.console import ConsoleWidget
  File "/Users/my-user/tasmota/tdm/venv/lib/python3.12/site-packages/tdmgr/GUI/console.py", line 20, in <module>
    from tdmgr.GUI.widgets import GroupBoxV, HLayout, VLayout, console_font
  File "/Users/my-user/tasmota/tdm/venv/lib/python3.12/site-packages/tdmgr/GUI/widgets.py", line 27, in <module>
    from tdmgr.tasmota.device import TasmotaDevice
  File "/Users/my-user/tasmota/tdm/venv/lib/python3.12/site-packages/tdmgr/tasmota/device.py", line 7, in <module>
    from pkg_resources import parse_version
ModuleNotFoundError: No module named 'pkg_resources'
```

This basically means `pyproject.toml` is missing a dependency for `setuptools`. This fixed it for me:
```
pip install setuptools
```

**Comment by jziolkowski** [comment]
thanks; it's been a while since I installed it from scratch :P I'll make sure it's fixed in next release next week
