### ISSUE TITLE
How to delete the config? Error after wrong Topic

### ISSUE THREAD

**Issue by iNDeX999** [jziolkowski/tdm#37]
Hi, i could not get any device from my IOBROKER. After some trys i ot this when i try to start tdm:

PS C:\ESP\tdm-master> python.exe .\tdm.py
Traceback (most recent call last):
  File ".\tdm.py", line 236, in mqtt_connected
    self.mqtt_subscribe()
  File ".\tdm.py", line 248, in mqtt_subscribe
    main_topics.append(self.device_model.commandTopic(idx))
  File "C:\ESP\tdm-master\Util\models.py", line 221, in commandTopic
    return self._devices[row][DevMdl.FULL_TOPIC].replace("%prefix%", "cmnd").replace("%topic%", self._devices[row][DevMdl.TOPIC])
AttributeError: 'NoneType' object has no attribute 'replace'

**Comment by jziolkowski** [comment]
Hello.

The confing file is in c:\users\<username>\TDM\tdm.cfg

Also I suggest you try the dev branch. It's much better at this time.

**Comment by iNDeX999** [comment]
Hi,

thank you, now the manager runs.

But how to add Devices? I think it will autodiscover my devices from the IOBROKER?

Regards
Markus

**Comment by jziolkowski** [comment]
In the dev version?

**Comment by iNDeX999** [comment]
Yes, now i use the dev version.

I´m connected to the IOBROKER by mqtt... 

And then ?

**Comment by jziolkowski** [comment]
what fulltopics are used by your device? TDM autodiscovers devices following the default fulltopic and the swapped one, used with HomeAssistant.

**Comment by iNDeX999** [comment]
![image](https://user-images.githubusercontent.com/53600396/64480284-24f04780-d1c5-11e9-8a20-93a94624fdb0.png)

**Comment by jziolkowski** [comment]
is the topic "sonoff" shared by all your devices? if yes, then it should be changed. Topic should be unique

**Comment by iNDeX999** [comment]
Ok, can i use the same name for topic and client?

**Comment by jziolkowski** [comment]
yes, this is irrelevant.

**Comment by iNDeX999** [comment]
ok, done. All tasmota devices changed.

I restartet the TDM ... nothing to see

**Comment by jziolkowski** [comment]
what do you see when you connect to your broker and subscribe to the following topic:
tele/#

**Comment by iNDeX999** [comment]
Sorry, i do´t know what you mean.

**Comment by jziolkowski** [comment]
do you use discord?

**Comment by iNDeX999** [comment]
sorry, no

**Comment by jziolkowski** [comment]
ok. 
you need a MQTT client, so you can connect to your broker to see the messages being delivered. 
Like this one: http://mqtt-explorer.com/

install it and connect to your broker. Then subscribe to the topic I wrote above

**Comment by iNDeX999** [comment]
I could not find where to subscribe to the topic, sorry
![image](https://user-images.githubusercontent.com/53600396/64480514-95996300-d1c9-11e9-8b1a-c151239575e4.png)

**Comment by jziolkowski** [comment]
oh right, mqtt explorer shows all topics. 
Does it show any messages? It should, if your devices are connected to the broker

**Comment by iNDeX999** [comment]
![image](https://user-images.githubusercontent.com/53600396/64480573-7bac5000-d1ca-11e9-8161-417f36fb357a.png)

**Comment by jziolkowski** [comment]
these are logs from iobroker, yes? I need MQTT traffic example.

**Comment by iNDeX999** [comment]
2019-09-07 23:53:44.371 - info: sonoff.0 starting. Version 2.2.2 in /opt/iobroker/node_modules/iobroker.sonoff, node: v10.16.3
--
2019-09-07 23:53:44.460 - info: sonoff.0 Starting MQTT authenticated server on port 1883
2019-09-07 23:53:45.175 - info: sonoff.0 Client [mqtt-explorer-cf35b990] connected with secret 1567893225157_7960
2019-09-07 23:53:45.372 - info: sonoff.0 new object created: sonoff.0.mqtt-explorer-cf35b990
2019-09-07 23:53:45.392 - info: sonoff.0 new object created: sonoff.0.mqtt-explorer-cf35b990.alive
2019-09-07 23:53:46.143 - info: sonoff.0 Client [0x3qQHnQ4dPLK3Fhl5R4MP] connected with secret 1567893226139_2672
2019-09-07 23:53:46.180 - info: sonoff.0 new object created: sonoff.0.0x3qQHnQ4dPLK3Fhl5R4MP
2019-09-07 23:53:46.206 - info: sonoff.0 new object created: sonoff.0.0x3qQHnQ4dPLK3Fhl5R4MP.alive
2019-09-07 23:53:52.114 - info: sonoff.0 Client [Sonoff-Mini-Steckdose-Garage] connected with secret 1567893232110_694
2019-09-07 23:53:52.306 - info: sonoff.0 Client [Sonoff-SV-Garage] connected with secret 1567893232304_4891
2019-09-07 23:53:52.330 - info: sonoff.0 Client [Sonoff-Steckdose-Router] connected with secret 1567893232328_5116
2019-09-07 23:53:52.646 - info: sonoff.0 Client [Sonoff-Dachfenster] connected with secret 1567893232645_594
2019-09-07 23:53:52.931 - info: sonoff.0 Client [Sonoff-433Bridge] connected with secret 1567893232929_6469

**Comment by jziolkowski** [comment]
this is not MQTT traffic. You should see messages being published to topics in mqtt explorer

**Comment by iNDeX999** [comment]
2019-09-07 23:56:32.345 - info: sonoff.0 starting. Version 2.2.2 in /opt/iobroker/node_modules/iobroker.sonoff, node: v10.16.3
--
2019-09-07 23:56:32.468 - info: sonoff.0 Starting MQTT authenticated server on port 1883
2019-09-07 23:56:32.491 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"","ack":true,"ts":1567893392475,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893392475}
2019-09-07 23:56:32.936 - debug: sonoff.0 stateChange sonoff.0.Sonoff-SV-Garage.alive: {"val":false,"ack":true,"ts":1567893392883,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893385649}
2019-09-07 23:56:32.937 - debug: sonoff.0 stateChange sonoff.0.Sonoff-433Bridge.alive: {"val":false,"ack":true,"ts":1567893392887,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893385656}
2019-09-07 23:56:32.937 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Mini-Steckdose-Garage.alive: {"val":false,"ack":true,"ts":1567893392890,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893385644}
2019-09-07 23:56:32.937 - debug: sonoff.0 stateChange sonoff.0.Tasmota-Manager.alive: {"val":false,"ack":true,"ts":1567893392893,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893224916}
2019-09-07 23:56:32.938 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Dachfenster.alive: {"val":false,"ack":true,"ts":1567893392896,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893385654}
2019-09-07 23:56:32.938 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Steckdose-Router.alive: {"val":false,"ack":true,"ts":1567893392899,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893385650}
2019-09-07 23:56:32.938 - debug: sonoff.0 stateChange sonoff.0.mqtt-explorer-cf35b990.alive: {"val":false,"ack":true,"ts":1567893392903,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893220466}
2019-09-07 23:56:32.938 - debug: sonoff.0 stateChange sonoff.0.0x3qQHnQ4dPLK3Fhl5R4MP.alive: {"val":false,"ack":true,"ts":1567893392905,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893220464}
2019-09-07 23:56:32.953 - info: sonoff.0 Client [0x3qQHnQ4dPLK3Fhl5R4MP] connected with secret 1567893392925_5850
2019-09-07 23:56:33.120 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP","ack":true,"ts":1567893393105,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893393105}
2019-09-07 23:56:33.384 - info: sonoff.0 Client [mqtt-explorer-cf35b990] connected with secret 1567893393381_6791
2019-09-07 23:56:33.396 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990","ack":true,"ts":1567893393387,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893393387}
2019-09-07 23:56:37.309 - info: sonoff.0 Client [Sonoff-Steckdose-Router] connected with secret 1567893397305_1590
2019-09-07 23:56:37.333 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990,Sonoff-Steckdose-Router","ack":true,"ts":1567893397314,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397314}
2019-09-07 23:56:37.350 - info: sonoff.0 Client [Sonoff-SV-Garage] connected with secret 1567893397330_4765
2019-09-07 23:56:37.369 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990,Sonoff-Steckdose-Router,Sonoff-SV-Garage","ack":true,"ts":1567893397357,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397357}
2019-09-07 23:56:37.382 - debug: sonoff.0 [Sonoff-SV-Garage] Received: cmnd/Sonoff-SV-Garage/POWER =
2019-09-07 23:56:37.390 - debug: sonoff.0 [Sonoff-Steckdose-Router] Received: cmnd/Sonoff-Steckdose-Router/POWER =
2019-09-07 23:56:37.424 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Steckdose-Router.alive: {"val":true,"ack":true,"ts":1567893397376,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397376}
2019-09-07 23:56:37.424 - debug: sonoff.0 stateChange sonoff.0.Sonoff-SV-Garage.POWER: {"val":false,"ack":true,"ts":1567893397408,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1564166187819}
2019-09-07 23:56:37.433 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Steckdose-Router.POWER: {"val":false,"ack":true,"ts":1567893397418,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893232392}
2019-09-07 23:56:37.434 - debug: sonoff.0 stateChange sonoff.0.Sonoff-SV-Garage.alive: {"val":true,"ack":true,"ts":1567893397427,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397427}
2019-09-07 23:56:37.437 - debug: sonoff.0 stateChange sonoff.0.Sonoff-SV-Garage.alive: {"val":true,"ack":true,"ts":1567893397431,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397427}
2019-09-07 23:56:37.659 - info: sonoff.0 Client [Sonoff-Dachfenster] connected with secret 1567893397657_629
2019-09-07 23:56:37.669 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990,Sonoff-Steckdose-Router,Sonoff-SV-Garage,Sonoff-Dachfenster","ack":true,"ts":1567893397662,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397662}
2019-09-07 23:56:37.686 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Dachfenster.alive: {"val":true,"ack":true,"ts":1567893397682,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397682}
2019-09-07 23:56:37.715 - debug: sonoff.0 [Sonoff-Dachfenster] Received: cmnd/Sonoff-Dachfenster/POWER =
2019-09-07 23:56:37.730 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Dachfenster.POWER: {"val":false,"ack":true,"ts":1567893397720,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567891354890}
2019-09-07 23:56:37.914 - info: sonoff.0 Client [Sonoff-433Bridge] connected with secret 1567893397912_1506
2019-09-07 23:56:37.965 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990,Sonoff-Steckdose-Router,Sonoff-SV-Garage,Sonoff-Dachfenster,Sonoff-433Bridge","ack":true,"ts":1567893397917,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397917}
2019-09-07 23:56:37.984 - debug: sonoff.0 [Sonoff-433Bridge] Received: cmnd/Sonoff-433Bridge/POWER =
2019-09-07 23:56:38.000 - debug: sonoff.0 stateChange sonoff.0.Sonoff-433Bridge.alive: {"val":true,"ack":true,"ts":1567893397978,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893397978}
2019-09-07 23:56:38.001 - debug: sonoff.0 stateChange sonoff.0.Sonoff-433Bridge.POWER: {"val":false,"ack":true,"ts":1567893397992,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1565518933518}
2019-09-07 23:56:38.145 - info: sonoff.0 Client [Sonoff-Mini-Steckdose-Garage] connected with secret 1567893398142_3532
2019-09-07 23:56:38.163 - debug: sonoff.0 stateChange sonoff.0.info.connection: {"val":"0x3qQHnQ4dPLK3Fhl5R4MP,mqtt-explorer-cf35b990,Sonoff-Steckdose-Router,Sonoff-SV-Garage,Sonoff-Dachfenster,Sonoff-433Bridge,Sonoff-Mini-Steckdose-Garage","ack":true,"ts":1567893398150,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893398150}
2019-09-07 23:56:38.189 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Mini-Steckdose-Garage.alive: {"val":true,"ack":true,"ts":1567893398182,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893398182}
2019-09-07 23:56:38.208 - debug: sonoff.0 [Sonoff-Mini-Steckdose-Garage] Received: cmnd/Sonoff-Steckdose-Garage/POWER =
2019-09-07 23:56:38.230 - debug: sonoff.0 stateChange sonoff.0.Sonoff-Mini-Steckdose-Garage.POWER: {"val":false,"ack":true,"ts":1567893398216,"q":0,"from":"system.adapter.sonoff.0","user":"system.user.admin","lc":1567893232188}
2019-09-07 23:56:47.399 - debug: sonoff.0 Client [Sonoff-Steckdose-Router] pingreq
2019-09-07 23:56:47.407 - debug: sonoff.0 Client [Sonoff-SV-Garage] pingreq
2019-09-07 23:56:47.751 - debug: sonoff.0 Client [Sonoff-Dachfenster] pingreq
2019-09-07 23:56:48.061 - debug: sonoff.0 Client [Sonoff-433Bridge] pingreq
2019-09-07 23:56:48.296 - debug: sonoff.0 Client [Sonoff-Mini-Steckdose-Garage] pingreq
2019-09-07 23:56:57.402 - debug: sonoff.0 Client [Sonoff-Steckdose-Router] pingreq
2019-09-07 23:56:57.426 - debug: sonoff.0 Client [Sonoff-SV-Garage] pingreq
2019-09-07 23:56:57.772 - debug: sonoff.0 Client [Sonoff-Dachfenster] pingreq
2019-09-07 23:56:58.093 - debug: sonoff.0 Client [Sonoff-433Bridge] pingreq
2019-09-07 23:56:58.329 - debug: sonoff.0 Client [Sonoff-Mini-Steckdose-Garage] pingreq

**Comment by jziolkowski** [comment]
Again, this is not MQTT output. MQTT explorer should show you messages being received from tasmota devices. This is output from ioborker logs. Different thing. I don't use IOBroker personally, so can't guide you there.

**Comment by iNDeX999** [comment]
MQTT Exp. shows nothing only "connected" and the "Topic"  part on the right is greyed out

![image](https://user-images.githubusercontent.com/53600396/64480702-ae574800-d1cc-11e9-9e8e-018b14a97270.png)


Thank you for your time, but i think it´s useless

**Comment by jziolkowski** [comment]
If your devices use the standard fulltopics, and are correctly connected to iobroker, and TDM as well, then the devices should show up immediately. There are too many variables in your setup outside of my control. I'd gladly help but I can't make sure everything talks correctly there.

**Comment by iNDeX999** [comment]
to bad, but i use tis config for all Tasmota devices ( except "Client" und after your hint "Topic" )

![image](https://user-images.githubusercontent.com/53600396/64480735-638a0000-d1cd-11e9-9ceb-1515c23ccf7c.png)

**Comment by jziolkowski** [comment]
I have no idea. It's getting late, I'll return to this issue tomorrow.

**Comment by iNDeX999** [comment]
Or does i think wrong. The Tasmota Device connects to the (Mqtt/IO)broker . TDM connects to the Broker too and subscriped to the same Topic as the Tasmota devices?

**Comment by jziolkowski** [comment]
the devices subscribe to their respective topics. TDM subscribes to tele/# and stat/# topics (and custom ones, if these are declared) and based on some tasmota logic and LWT messages, it autodiscovers them. That's why I wanted you to show me bare MQTT chatter, to see if all things see each other.

**Comment by jziolkowski** [comment]
BTW it would be beneficial for you to make an account on Discord, because Tasmota has this great support server there, and soon i'm starting a similar one for TDM

**Comment by iNDeX999** [comment]
Hi, i´m on Discord now ;)

**Comment by Jason2866** [comment]
Since TDM 0.2 is released, this issue is outdated
