### ISSUE TITLE
Right click crashes the application

### ISSUE THREAD

**Issue by defconhaya** [jziolkowski/tdm#46]
When right click on device list (empty one) the app crash with the following message

> Traceback (most recent call last):
  File "D:\ESP8266\Tasmota Device Manager\GUI\Devices.py", line 312, in show_list_ctx_menu
    self.select_device(self.device_list.indexAt(at))
  File "D:\ESP8266\Tasmota Device Manager\GUI\Devices.py", line 317, in select_device
    self.device = self.model.deviceAtRow(self.idx.row())
  File "D:\ESP8266\Tasmota Device Manager\Util\models.py", line 30, in deviceAtRow
    return self.tasmota_env.devices[row]
IndexError: list index out of range

**Comment by jziolkowski** [comment]
Fixed :)
