### ISSUE TITLE
Crashes when selecting 'Rules and Timers'

### ISSUE THREAD

**Issue by ScrewLooseDan** [jziolkowski/tdm#5]
From the Configure menu, when I switch to the "Rules and Timers" tab tdm crashes and I get the following error:
```
Traceback (most recent call last):
  File "<full file path removed>tdm/GUI/DeviceConfig.py", line 155, in mqtt_message
    self.parseTimer(msg[first])
  File "<full file path removed>/tdm/GUI/DeviceConfig.py", line 371, in parseTimer
    self.cbxTimerOut.setCurrentIndex(payload['Output']-1)
KeyError: 'Output'
Aborted
```
I have no rules or timers setup, so perhaps that would be the reason?

**Comment by jziolkowski** [comment]
No rules or timers set up, or not in the firmware?
What's the output of command `timers`?

**Comment by ScrewLooseDan** [comment]
I guess more correctly, I don't use any timers and they are defaults.

```
stat/bedroom/RESULT {"Timers":"OFF"}
stat/bedroom/RESULT {"Timers1":{"Timer1":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer2":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer3":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer4":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0}}}
stat/bedroom/RESULT {"Timers2":{"Timer5":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer6":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer7":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer8":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0}}}
stat/bedroom/RESULT {"Timers3":{"Timer9":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer10":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer11":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer12":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0}}}
stat/bedroom/RESULT {"Timers4":{"Timer13":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer14":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer15":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0},"Timer16":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Action":0}}}
```

**Comment by jziolkowski** [comment]
Ok, there's indeed a key missing. Which FW version you have? In the Timers config in the WebUI, do you have an "Output" combobox?

**Comment by jziolkowski** [comment]
Ok, I think I found the reason. Do you have any relays configured?

**Comment by ScrewLooseDan** [comment]
I'm using 6.4.1.  I don't see anything obvious listed as Output on the timers page.
These devices are Wemos with sensors, no relays.

**Comment by jziolkowski** [comment]
And that's the reason. I'll push a fix in few mins.

**Comment by ScrewLooseDan** [comment]
Thanks!

**Comment by jziolkowski** [comment]
Done, ready to pull. Thanks for the bug report.

**Comment by ScrewLooseDan** [comment]
No problem.  Working now!
