### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

### ISSUE THREAD

**Issue by mkyral** [jziolkowski/tdm#6]
Hi,
I just found this nice program, but can't it work. I have one PowR2, I added manually, but details are not shown. In console is this error shown:
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/usr/lib64/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 2650, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 1481, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 1003, in loop
    rc = self.loop_read(max_packets)
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 1284, in loop_read
    rc = self._packet_read()
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 1849, in _packet_read
    rc = self._packet_handle()
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 2305, in _packet_handle
    return self._handle_publish()
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 2500, in _handle_publish
    self._handle_on_message(message)
  File "/home/marian/.local/lib64/python3.6/site-packages/paho/mqtt/client.py", line 2647, in _handle_on_message
    self.on_message(self, self._userdata, message)
  File "/home/marian/programy/tdm/Util/mqtt.py", line 144, in on_message
    mstr = msg.payload.decode("ascii")
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 6: ordinal not in range(128)

```

The mqtt messages (generated when I click on mqtt button)

```
cmnd/PowR2/status (null)
cmnd/PowR2/status 1
cmnd/PowR2/status 2
cmnd/PowR2/status 3
cmnd/PowR2/status 5
cmnd/PowR2/status 8
cmnd/PowR2/status 11
stat/PowR2/STATUS {"Status":{"Module":43,"FriendlyName":["Sonoff POW R2"],"Topic":"PowR2","ButtonTopic":"0","Power":0,"PowerOnState":3,"LedState":1,"SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
stat/PowR2/STATUS1 {"StatusPRM":{"Baudrate":4800,"GroupTopic":"sonoffs","OtaUrl":"http://thehackbox.org/tasmota/release/sonoff-CZ.bin","RestartReason":"Power on","Uptime":"34T04:29:36","StartupUTC":"2019-01-20T09:13:16","Sleep":0,"BootCount":18,"SaveCount":202,"SaveAddress":"FA000"}}
stat/PowR2/STATUS2 {"StatusFWR":{"Version":"6.3.0","BuildDateTime":"2018-10-30T17:38:46","Boot":6,"Core":"2_3_0","SDK":"1.5.3(aec24ac9)"}}
stat/PowR2/STATUS3 {"StatusLOG":{"SerialLog":2,"WebLog":2,"SysLog":0,"LogHost":"","LogPort":514,"SSId":["my_ssid",""],"TelePeriod":300,"SetOption":["000A8009","55818000","00000000"]}}
stat/PowR2/STATUS5 {"StatusNET":{"Hostname":"Sonoff_PowR2","IPAddress":"192.168.1.70","Gateway":"192.168.1.1","Subnetmask":"255.255.255.0","DNSServer":"192.168.1.1","Mac":"80:xx:xx:xx:xx:xx","Webserver":2,"WifiConfig":5}}
stat/PowR2/STATUS8 {"StatusSNS":{"Time":"2019-02-23T14:42:53","ENERGY":{"TotalStartTime":"2018-10-31T20:32:18","Total":12.163,"Yesterday":0.000,"Today":0.000,"Power":0,"ApparentPower":0,"ReactivePower":0,"Factor":0.00,"Voltage":0,"Current":0.000}}}
stat/PowR2/STATUS11 {"StatusSTS":{"Time":"2019-02-23T14:42:53","Uptime":"34T04:29:37","Vcc":3.219,"POWER":"OFF","Wifi":{"AP":1,"SSId":"my_ssid","BSSId":"BC:xx:xx:xx:xx:xx","Channel":8,"RSSI":76}}}
```
I'm on Gentoo linux, python 3.6.5, paho-mqt 1.3.1.

Any idea? Could this  been caused by Czech FW?

**Comment by jziolkowski** [comment]
Yes, this is related to some Czech character accents. I'll see what I can do.
Does your device send any accents for tasmota via mqtt?

**Comment by mkyral** [comment]
I just added a debug message and it fails on 
```
topic: tele/PowR2/LWT / payload: b'Aktivn\xc3\xad'
Exception in thread Thread-1:
```
Should be "Aktivní" and means "active".

**Comment by mkyral** [comment]
After change "ascii" to "utf-8" it continues, but crash on:

```
topic: tele/PowR2/LWT / payload: b'Aktivn\xc3\xad'
Traceback (most recent call last):
  File "/home/marian/programy/tdm/Util/models.py", line 513, in paint
    x = option.rect.center().x()+1 - px.rect().width() / 2
AttributeError: 'NoneType' object has no attribute 'rect'

```

**Comment by jziolkowski** [comment]
ok, I see the LWT is localized.

**Comment by jziolkowski** [comment]
BTW, what are your outputs for POWER state?

**Comment by mkyral** [comment]
This I get when I connect to mqtt:
```
$ mosquitto_sub -h 192.168.1.1 -v -t '#' |grep tele
homeassistant/switch/PowR2_1/config {"name":"Sonoff POW R2","command_topic":"cmnd/PowR2/POWER","state_topic":"stat/PowR2/RESULT","value_template":"{{value_json.POWER}}","payload_off":"OFF","payload_on":"ON","availability_topic":"tele/PowR2/LWT","payload_available":"Aktivní","payload_not_available":"Neaktivní"}
tele/PowR2/LWT Aktivní
```
It seems like HomeAssistent config.

Ad POWER - is this it ?
```
tele/PowR2/STATE {"Time":"2019-02-23T17:36:59","Uptime":"34T07:23:43","Vcc":3.219,"POWER":"OFF","Wifi":{"AP":1,"SSId":"maros_home_nett","BSSId":"BC:xx:xx:xx:xx:xx","Channel":8,"RSSI":64}}
```

**Comment by jziolkowski** [comment]
No, when you chose localized firmware, some mqtt values are localized.
I've pushed a temporary workaround. For the time being, the device will show undefined LWT, but should work otherwise. I'll add some GUI config options to input localization values.

**Comment by mkyral** [comment]
And what about reporting a bug to Tasmota?

**Comment by mkyral** [comment]
> No, when you chose localized firmware, some mqtt values are localized.
> I've pushed a temporary workaround. 

It still crashing:
```
Traceback (most recent call last):
  File "/home/marian/programy/tdm/Util/models.py", line 513, in paint
    x = option.rect.center().x()+1 - px.rect().width() / 2
AttributeError: 'str' object has no attribute 'rect'

```

**Comment by jziolkowski** [comment]
try now.

Also it's not a bug in Tasmota. It's by design.

**Comment by mkyral** [comment]
Great. Works now.
Thanks a lot.
