### ISSUE TITLE
Crash when programming timer

### ISSUE THREAD

**Issue by eku** [jziolkowski/tdm#76]
Reproducable crash when programming timer > 1

```
Traceback (most recent call last):
  File ".../tdm/lib/python3.7/site-packages/GUI/Timers.py", line 118, in loadTimer
    payload = self.timers[timer]
KeyError: 'Timer2'
Abgebrochen (Speicherabzug geschrieben)
```

```
Traceback (most recent call last):
  File ".../tdm/lib/python3.7/site-packages/GUI/Timers.py", line 238, in parseMessage
    self.loadTimer(self.cbTimer.currentText())
  File ".../tdm/lib/python3.7/site-packages/GUI/Timers.py", line 134, in loadTimer
    self.TimerMode.button(mode).setChecked(True)
AttributeError: 'NoneType' object has no attribute 'setChecked'
Abgebrochen (Speicherabzug geschrieben)
```

```
pip3 list
Package       Version
------------- -------
paho-mqtt     1.5.0  
pip           19.3.1 
PyQt5         5.14.0 
PyQt5-sip     12.7.0 
PyQtWebEngine 5.14.0 
setuptools    42.0.2 
tdmgr         0.2.6  
wheel         0.33.6 
```

System: Fedora 31

**Comment by jziolkowski** [comment]
I can't reproduce this error. I have an idea but I need output of `status 0` and `timers` command

**Comment by eku** [comment]
Which valus from ```status 0``` are you interested on?

```
17:23:22 MQT: stat/esp5/RESULT = {"Timers":"on"}
17:23:22 MQT: stat/esp5/RESULT = {"Timers1":{"Timer1":{"Arm":1,"Mode":0,"Time":"22:00","Window":0,"Days":"1111100","Repeat":1,"Output":1,"Action":0},"Timer2":{"Arm":1,"Mode":0,"Time":"23:55","Window":0,"Days":"0000011","Repeat":1,"Output":1,"Action":0},"Timer3":{"Arm":1,"Mode":0,"Time":"05:15","Window":0,"Days":"0111110","Repeat":1,"Output":1,"Action":1},"Timer4":{"Arm":1,"Mode":0,"Time":"08:00","Window":0,"Days":"1000001","Repeat":1,"Output":1,"Action":1}}}
17:23:22 MQT: stat/esp5/RESULT = {"Timers2":{"Timer5":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer6":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer7":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer8":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0}}}
17:23:22 MQT: stat/esp5/RESULT = {"Timers3":{"Timer9":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer10":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer11":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer12":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0}}}
17:23:22 MQT: stat/esp5/RESULT = {"Timers4":{"Timer13":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer14":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer15":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0},"Timer16":{"Arm":0,"Mode":0,"Time":"00:00","Window":0,"Days":"0000000","Repeat":0,"Output":1,"Action":0}}}```

**Comment by jziolkowski** [comment]
all of status 0. Redact your wifi settings if you want.
Also, is the bug still there?

**Comment by eku** [comment]
Sensitive data replaced by dash.

```MQT: stat/esp5/STATUS = {"Status":{"Module":0,"FriendlyName":["-"],"Topic":"-","ButtonTopic":"0","Power":1,"PowerOnState":3,"LedState":0,"LedMask":"FFFF","SaveData":1,"SaveState":1,"SwitchTopic":"0","SwitchMode":[0,0,0,0,0,0,0,0],"ButtonRetain":0,"SwitchRetain":0,"SensorRetain":0,"PowerRetain":0}}
MQT: stat/esp5/STATUS1 = {"StatusPRM":{"Baudrate":4800,"GroupTopic":"tasmotas","OtaUrl":"-","RestartReason":"Software/System restart","Uptime":"2T22:13:18","StartupUTC":"2020-01-21T16:39:37","Sleep":200,"CfgHolder":4617,"BootCount":42,"SaveCount":244,"SaveAddress":"FA000"}}
MQT: stat/esp5/STATUS2 = {"StatusFWR":{"Version":"8.1.0(tasmota)","BuildDateTime":"2019.12.25 12:47:07","Boot":31,"Core":"2_6_1","SDK":"2.2.2-dev(38a443e)","Hardware":"ESP8266EX","CR":"341/699"}}
MQT: stat/esp5/STATUS3 = {"StatusLOG":{"SerialLog":2,"WebLog":2,"MqttLog":0,"SysLog":2,"LogHost":"-","LogPort":514,"SSId":["-","-"],"TelePeriod":300,"Resolution":"558180C0","SetOption":["04008009","2805C8000100068000005AFF000000000000","00000001","00000000"]}}
MQT: stat/esp5/STATUS4 = {"StatusMEM":{"ProgramSize":567,"Free":436,"Heap":23,"ProgramFlashSize":1024,"FlashSize":1024,"FlashChipId":"146085","FlashMode":3,"Features":["00000407","8FDAE397","043683A0","22B617CD","01001BC0","00007881"],"Drivers":"1,2,3,4,5,6,7,8,9,10,12,16,18,19,20,21,22,24,26,29","Sensors":"1,2,3,4,5,6,7,8,9,10,14,15,17,18,20,22,26,34"}}
MQT: stat/esp5/STATUS5 = {"StatusNET":{"Hostname":"-","IPAddress":"-","Gateway":"-","Subnetmask":"255.255.255.0","DNSServer":"-","Mac":"-","Webserver":2,"WifiConfig":2}}
MQT: stat/esp5/STATUS6 = {"StatusMQT":{"MqttHost":"-","MqttPort":1883,"MqttClientMask":"DVES_%06X","MqttClient":"DVES_3E57F3","MqttUser":"DVES_USER","MqttCount":4,"MAX_PACKET_SIZE":1000,"KEEPALIVE":30}}
MQT: stat/esp5/STATUS7 = {"StatusTIM":{"UTC":"Fri Jan 24 14:52:55 2020","Local":"Fri Jan 24 15:52:55 2020","StartDST":"Sun Mar 29 02:00:00 2020","EndDST":"Sun Oct 25 03:00:00 2020","Timezone":99,"Sunrise":"08:30","Sunset":"17:33"}}
MQT: stat/esp5/STATUS10 = {"StatusSNS":{"Time":"2020-01-24T15:52:55"}}
MQT: stat/esp5/STATUS11 = {"StatusSTS":{"Time":"2020-01-24T15:52:55","Uptime":"2T22:13:18","UptimeSec":252798,"Heap":22,"SleepMode":"Dynamic","Sleep":200,"LoadAvg":4,"MqttCount":4,"POWER1":"on","Wifi":{"AP":1,"SSId":"-","BSSId":"-","Channel":6,"RSSI":100,"Signal":-41,"LinkCount":2,"Downtime":"0T00:00:07"}}}```

**Comment by ramanraja** [comment]
My issue is slightly different in details, as it appears to be a JSON issue. But it relates to the same timer crash. So I am attaching it in this thread:

TDM: version 0.2.6, Source cloned from Git.
Python: version (Anaconda) 3.7.9
Tasmota: 
  Program Version	8.5.1(tasmota)
  Build Date & Time	2020-10-02T10:09:47
  Core/SDK Version	2_7_4_1/2.2.2-dev(38a443e)

Scenario: 
  Start TDM as a Python script.
  Connect to local Mosquitto server.
  All 10 Tasmota devices are discovered.
  Select any one and click the menu itm 'timers'
  The program crashes with the following dump:

(tdm) C:\Arduino\TDM>python tdmgr.py
Traceback (most recent call last):
  File "C:\Arduino\TDM\GUI\Timers.py", line 238, in parseMessage
    self.loadTimer(self.cbTimer.currentText())
  File "C:\Arduino\TDM\GUI\Timers.py", line 122, in loadTimer
    self.cbTimerArm.setChecked(payload['Arm'])
KeyError: 'Arm'

**Comment by eku** [comment]
@ramanraja yours is #101

**Comment by ramanraja** [comment]
Thanks. Is this fix reverted for some reason? I cloned the repo only today (14 Oct 20), but got the error.

**Comment by jziolkowski** [comment]
This fix is still pending for version 0.3

**Comment by Jason2866** [comment]
Please try latest version

**Comment by eku** [comment]
@jziolkowski Version `0.2.8? does not crash anymore, but you cannot program a timer. In the dialog `Timers` I activate the checkbox `Enabled` and the dialog is unlocked and to be locked again in the same second without me doing anything.
